@startuml manager
left to right direction
actor Manager
rectangle "System" as system {
  (Login)
  (Register)
  (View Movies)
  (Add Movie)
  (Remove Movie)
  (Generate Ticket)
  (Logout)
}
Manager --> (Login)
Manager --> (Register)
Manager --> (View Movies)
Manager --> (Add Movie)
Manager --> (Remove Movie)
Manager --> (Generate Ticket)
Manager --> (Logout)
@enduml