@startuml paymentsystem
left to right direction
actor PaymentSystem
rectangle "System" as system {
  (Authorize)
  (Capture)
  (Refund)
  (Cancel)
  (Verify)
}
PaymentSystem --> (Authorize)
PaymentSystem --> (Capture)
PaymentSystem --> (Refund)
PaymentSystem --> (Cancel)
PaymentSystem --> (Verify)
@enduml