@startuml searchengine
left to right direction
actor SearchEngine
rectangle "System" as system {
  (Search)
  (Filter)
  (Display Result)
}
SearchEngine --> (Search)
SearchEngine --> (Filter)
SearchEngine --> (Display Result)
@enduml