@startuml searchengine
left to right direction
actor SearchEngine
rectangle "System" as system {
  (Get_User_Input)
  (Display_Result)
}
SearchEngine --> (Search_Per_User_Input)
SearchEngine --> (Display_Result)
@enduml